In [1]:
import pandas as pd

# Step 1: Load the dataset
df = pd.read_csv('Fdum Data.csv')

# Step 2: Perform one-hot encoding on 'Country' and 'Purchased'
df_encoded = pd.get_dummies(df, columns=['Country', 'Purchased'], drop_first=True)

# Show result
print(df_encoded)

   Age  Salary  Country_Germany  Country_Spain  Purchased_Yes
0   44   72000            False          False          False
1   27   48000            False           True           True
2   30   54000             True          False          False
3   38   61000            False           True          False
4   40   85000             True          False           True
5   35   58000            False          False           True
6   31   52000            False           True          False
7   48   79000            False          False           True
8   50   83000             True          False          False
9   37   67000            False          False           True